### ISSUE TITLE
[BUG]: Unable to connect to import list - all lists fail apart from one

### ISSUE THREAD

**Issue by triksmelb** [lidarr/LidarrAPI.Metadata#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to add any Lidarr lists **except** for Last.fm Top Artists.

Logs:

Unable to connect to import list: HTTP request failed: [500:InternalServerError] [GET] at [https://api.lidarr.audio/api/v0.4/chart/billboard/album/top]

NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.lidarr.audio/api/v0.4/chart/billboard/album/top]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchImportListResponse(ImportListRequest request) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 198
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 184
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 212
{"error":"Internal server error"}

HTTP Error - Res: [GET] https://api.lidarr.audio/api/v0.4/chart/billboard/album/top: 500.InternalServerError
{"error":"Internal server error"}

### Expected Behavior

Ability to test and add all indexers successfully.

### Steps To Reproduce

Tried to add and remove all indexers.
Manually tried to navigate to indexer URL.

### Environment

```markdown
- OS: Synology DSM
- Lidarr:0.8.1.2135 (linuxserver.io)
- .net Core: Yes (3.1.13)
- Docker Install: Yes 
- Using Reverse Proxy: No
- Browser: Safari 15.1
```

### What branch are you running?

Master

### Anything else?

Nothing else.

[AB#1929](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1929)

[AB#1930](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1930)

**Comment by danielunderwood** [comment]
#191 fixed many errors, but iTunes and Apple Music recent albums are still broken.
