### ISSUE TITLE
Specific artist request ends in internal server error

### ISSUE THREAD

**Issue by Dalethium** [lidarr/LidarrAPI.Metadata#227]
https://api.lidarr.audio/api/v0.4/search?type=all&query=vivivivivi results in internal server error
https://api.lidarr.audio/api/v0.4/search?type=all&query=test does not

As a note, that is an actual artist.  https://www.last.fm/music/vivivivivi/

If you need more info let me know but I think since it's an internal server error on the API it is something you'd have the logs for. I came to that API endpoint from my lidarr server logs

```
2022-12-02 10:17:51 [Warn] HttpClient: HTTP Error - Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=all&query=vivivivivi: 500.InternalServerError (33 bytes)
2022-12-02 10:17:51 {"error":"Internal server error"} 
2022-12-02 10:17:51 [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 
2022-12-02 10:17:51 
2022-12-02 10:17:51 [v1.0.2.2592] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'vivivivivi' failed. Unable to communicate with LidarrAPI.
2022-12-02 10:17:51    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewEntity(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 370
2022-12-02 10:17:51    at lambda_method238(Closure , Object , Object[] )
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
2022-12-02 10:17:51 --- End of stack trace from previous location ---
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2022-12-02 10:17:51 --- End of stack trace from previous location ---
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2022-12-02 10:17:51    at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\BufferingMiddleware.cs:line 28
2022-12-02 10:17:51    at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
2022-12-02 10:17:51    at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
2022-12-02 10:17:51    at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
2022-12-02 10:17:51    at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Lidarr.Http\Middleware\VersionMiddleware.cs:line 28
2022-12-02 10:17:51    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2022-12-02 10:17:51    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2022-12-02 10:17:51
```

[AB#4256](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4256)

**Comment by Dalethium** [comment]
https://www.last.fm/music/vivivivivi is the artist, I linked a youtuber by the same name by mistake sorry.

**Comment by ta264** [comment]
Can you find the artist on musicbrainz?  That's the source of lidarr's metadata.

**Comment by Dalethium** [comment]
https://musicbrainz.org/artist/bee49740-e968-44d2-859a-aa9722049e08 This should be it!

**Comment by ta264** [comment]
Resolved
