### ISSUE TITLE
 KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by ptichalouf** [lidarr/LidarrAPI.Metadata#242]
i'm on proxmox with this : 

Version
    2.6.4.4402
.NET
    Yes (6.0.32)
Database
    Sqlite 3.40.1
Database Migration
    79
AppData Directory
    /var/lib/lidarr
Startup Directory
    /opt/Lidarr
Mode
    Console
Uptime

And i got this error i can't import list

Message
The given key '1a0c3cd4-0161-4f68-a0fd-f45983179944' was not present in the dictionary.: The given key '1a0c3cd4-0161-4f68-a0fd-f45983179944' was not present in the dictionary.
Exception
System.Collections.Generic.KeyNotFoundException: The given key '1a0c3cd4-0161-4f68-a0fd-f45983179944' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapTrack(TrackResource resource, Dictionary`2 artistDict) in ./Lidarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 543
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapRelease(ReleaseResource resource, Dictionary`2 artistDict) in ./Lidarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 503
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapAlbum(AlbumResource resource, Dictionary`2 artistDict) in ./Lidarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 473
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetAlbumInfo(String foreignAlbumId) in ./Lidarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 148
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewAlbum(String title, String artist) in ./Lidarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 308

**Comment by bakerboy448** [comment]
GitHub is not for support
The metadata repo is not for lidarr issues.


For support and inquiries, please use our [Discord](http://lidarr.audio/discord) channel. GitHub is designated solely for bug reports and feature requests. It seems that this issue may fall under a support request, so we kindly ask you to visit our Discord for assistance. Thank you.
